name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout test cases
        uses: actions/checkout@v2
        with:
          repository: prabhatram/PROG2_2024_TEST_PRIVATE
          ref: main
          path: tests

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Compile student's code
        run: javac -d bin src/*.java

      - name: Compile and run tests
        run: |
          javac -cp bin:tests/junit-4.13.2.jar -d bin-tests tests/*.java
          java -cp bin:bin-tests:tests/junit-4.13.2.jar org.junit.runner.JUnitCore AppTest
